<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE content [
	<!ELEMENT content (title, sumary, intro?, subsections*)>
		<!ATTLIST content id ID #REQUIRED>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT sumary (item+)>
		<!ELEMENT intro (#PCDATA)>
		<!ELEMENT subsections (subsection*)>
			<!ELEMENT subsection (subtitle, subcontent)>
				<!ATTLIST subsection id ID #REQUIRED level CDATA #REQUIRED>
				<!ELEMENT subtitle (#PCDATA)>
				<!ELEMENT subcontent (text | image | list | subsections)*>
					<!ELEMENT text (#PCDATA)>
					<!ELEMENT image (#PCDATA)>
					<!ELEMENT list (item+)>
						<!ELEMENT item (#PCDATA)>
							<!ATTLIST item ref IDREF #IMPLIED>

]>

<content id="attacks">
	<title>Attacks on Firewall</title>
	
	<sumary>
		<item ref="types">Types of Attacks</item>
		<item ref="compensating_measures">Compensating Measures</item>
		<item ref="final-considerations">Final Consideration</item>
	</sumary>
	
	<intro>
		Given the understanding on how firewall works and its importance, one must consider how this security technology can be breached. This page lists 5 classes of attacks, which target firewalls, or target the systems that firewalls are supposed to protect. Each of the attacks described here were designed to penetrate only one layer of firewalls. In practice, firewalls are deployed in many layers separating the Internet from industrial control and safety networks. However, we assume that if one layer of firewalls can be breached, then new attacks can be mounted on the next layer of firewalls in the layered defensive architecture.
	</intro>
	
	<subsections>
		<subsection id="types" level="1">
			<subtitle>Types of Attacks</subtitle>
			<subcontent>
				<subsections>
					<subsection id="password-stealing" level="2">
						<subtitle>Password Stealing</subtitle>
						<subcontent>
							<text>
								Password Stealing is the type of attack where, as the name itself suggests, the attacker obtains access to one or more password registered in the system protected by the firewall. These passwords can be obtained in many ways, for example the attacker can send emails through a firewall to persuade recipients to either reveal passwords or to download and run a malware that steals the recipient’s password. Another way to steal passwords is by social engineering – look under a victim’s keyboard, or look for a sticky note on their monitor, or shoulder-surf while they type their password. More exotic password theft is accomplished by tricking people into installing keystroke loggers, which are programs that record every key pressed by the user. 
							</text>
						</subcontent>
					</subsection>
					<subsection id="external_assets" level="2">
						<subtitle>Attacks on External Assets</subtitle>
						<subcontent>
							<text>
								Attacks on external assets can happen when control systems rely on IT domain controllers, domain name servers (DNS), or enterprise resource planning (ERP) servers for example, even though those external servers are not managed as safety-critical or reliability-critical assets. If these external assets are vulnerable to buffer-overflow, SQL-injection, cross-site scripting, denial-of-service, and a host of other kinds of attacks, an attacker can compromise a domain controller and simply change existing passwords or create their own accounts and passwords. 
							</text>
							<text>
								Industrial client software is just as vulnerable as industrial servers. A compromised server on an external network, such as the business network, can propagate attacks back into industrial clients. For example: pull a file from a virus-infected file server, and now there is a virus on the industrial network. Pull a web page from a compromised web server, and drive-by malware can wind up on the industrial network. 
							</text>
						</subcontent>
					</subsection>
					<subsection id="network" level="2">
						<subtitle>Attack on the Network</subtitle>
						<subcontent>
							<text>
								Systems are susceptible to attacks on the network when the protocols used are bad implemented and vulnerable to man-in-the-middle attacks, which allows attackers to insert their own commands into existing, authenticated communications streams. Another weakness that the network can have resides on the possibility of providing VPN account and password. A malware in control of a computer can jump across VPN connections terminating in that computer, and a compromised computer coupled with split tunneling enabled allows distant attackers to launch interactive remote control attacks on industrial assets across VPN connections. 
							</text>
						</subcontent>
					</subsection>
					<subsection id="firewall_vulnerabilities" level="2">
						<subtitle>Firewall Vulnerabilities</subtitle>
						<subcontent>
							<text>
								Firewalls are software and, as all modern software, it has defects. Some of these defects can represent security vulnerabilities. Some firewall vulnerabilities, such as cross-site scripting vulnerabilities in HTTP-based “VPN” proxy servers, are design vulnerabilities and they may never be corrected because the designed and desired operation of the software can only be done if these vulnerabilities exist. Most firewall rules are expressed in terms of IP addresses or ranges of IP addresses. Forging an IP address is often enough to persuade a firewall to accept at least some communications from an attacker. 
							</text>
						</subcontent>
					</subsection>
					<subsection id="physical_access" level="2">
						<subtitle>Physical Access</subtitle>
						<subcontent>
							<text>
								Complex networks may have non-obvious, unprotected paths from business networks to industrial networks. Well-meaning insiders may set up rogue wireless access points on critical networks. With many firewalls, if an attacker can touch the device, they can compromise it. Some firewalls have administrative ports that permit unauthenticated access to change configurations. Most firewalls can be physically reset to factory defaults and reprogrammed, or the firewall can simply be physically replaced with a router. 
							</text>
						</subcontent>
					</subsection>
				</subsections>
			</subcontent>
		</subsection>

		<subsection id="compensating_measures" level="1">
			<subtitle>Alternatives and Compensating Measures</subtitle>
			<subcontent>
				<subsections>
					<subsection id="two-factor" level="2">
						<subtitle>2-Factor Authentication</subtitle>
						<subcontent>
							<text>
								2-Factor Authentication is the use of biometrics, smart cards, or some other measure in addition to a password to identify and authenticate individuals seeking to access protected equipment. 2-factor authentication is used regularly on remote access mechanisms for industrial networks but is used much less commonly inside industrial networks, in part because of concerns about slowing down emergency response in safety emergencies.
							</text>
						</subcontent>
					</subsection>
					<subsection id="encryption" level="2">
						<subtitle>Encryption</subtitle>
						<subcontent>
							<text>
								Encryption is the use of cryptosystems to protect either the confidentiality or authenticity of data communications mechanisms. Encryption is starting to be used fairly routinely in client/server interfaces for modern control systems, and these are the communications most likely to pass through a firewall. Encryption is occasionally used when data must pass across wireless networks or wide-area networks. Encryption tends not to be used when communicating between distributed control system (DCS) software and programmable logic controllers (PLCs) or other devices.
							</text>
						</subcontent>
					</subsection>
					<subsection id="firewall-rules" level="2">
						<subtitle>Firewalls Rules</subtitle>
						<subcontent>
							<text>
								Firewalls themselves can protect against some attacks if their configurations and rules are improved or made more specific.
							</text>
						</subcontent>
					</subsection>
					<subsection id="hids-nids" level="2">
						<subtitle>HIDS and NIDS</subtitle>
						<subcontent>
							<text>
								Host intrusion detection and intrusion prevention systems (HIDS) can detect and/or prevent certain classes of suspicious activities. Anti-virus systems, application control/whitelisting systems, removable device controls, and file-change monitoring all fit here. These are all technologies intended to harden the typically “soft interior” of control networks.
							</text>
							<text>
								Network intrusion detection and intrusion prevention systems (NIDS) can detect and/or prevent certain classes of suspicious communications. These systems may be separate appliances, or they may be built into firewalls. These systems may be signature-based systems or may be learning-based or anomaly-based systems as well.
							</text>
						</subcontent>
					</subsection>
					<subsection id="patch" level="2">
						<subtitle>Updated Patch</subtitle>
						<subcontent>
							<text>
								Security update programs or “patch” programs regularly test and install updated versions of software and operating systems to repair the software defects, which are security vulnerabilities. Patch programs are particularly challenging for change-controlled networks because of the risks to safety and to reliability that are inherent in any changes to executable code.
							</text>
						</subcontent>
					</subsection>
					<subsection id="usg" level="2">
						<subtitle>Unidirectional Security Gateways</subtitle>
						<subcontent>
							<text>
								Unidirectional security gateways allow information to flow out of a protected industrial network but are physically unable to send any attack or communication at all back into the industrial network. The gateways replicate industrial servers to business networks. Business applications and business users access only the replica servers.
							</text>
						</subcontent>
					</subsection>
				</subsections>
			</subcontent>
		</subsection>

		<subsection id="final-considerations" level="1">
			<subtitle>Final Considerations</subtitle>
			<subcontent>
				<text>
					These different types of attacks on firewalls are not surprising to security authorities. The ISA-99 series of standards, NERC-CIP, API 1164, and many other industrial security standards and guidance have a great deal to say about how any firewall must be managed in order for it to remain somewhat secure. They describe a set processes, procedures, testing, reviews, audits, documentation, and other recommended activities that must be adopted by the pratitioner in order to build a proper firewall.
				</text>
				<text>
					The main recomendation to pratitioners is to deeply understanting the security technology that one wants to implement in order to set up the appropriate compensating measures for possible vulnerabilities in the system. Another issue that the pratitioner must be aware of is the trade-off between the system's security and the system's flexibility. Until what point is worth to reduce the user's freedrom to protect the system? When does the security measures start to affect the coorporation process per se? These are some questions that must be carefully analyzed before implementing a security technology, such as firewalls.
				</text>
			</subcontent>
		</subsection>
	</subsections>
</content>